[package]
name = "fm-controller-agent"
description = "Agent CRD and Controller for ForgeMaster"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "fm-controller-agent"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
fm-controller-agenttask = { workspace = true }
kube = { workspace = true }
uuid = { workspace = true }
k8s-openapi = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
typed-builder = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
dashmap = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
