{{- if .Values.controller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fm-controller-agent
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: fm-controller-agent
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: forgemaster
{{- end }}
