---
forgemaster_namespace: forgemaster-system
fm_controller_agent_chart: "{{ playbook_dir }}/../crates/fm-controller-agent/helm"
fm_controller_agent_crd_enabled: true
fm_controller_agent_controller_enabled: false
